use std::env;
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};

#[path = "src/partition.rs"]
mod partition;

use partition::{
    BOOTLOADER_REGION, MCU_BOOT_LAYOUT, PRIMARY_SLOT_REGION, PartitionLayout, SCRATCH_REGION,
    SECONDARY_SLOT_REGION, SETTINGS_REGION,
};

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").expect("missing target arch");
    let target_os = env::var("CARGO_CFG_TARGET_OS").expect("missing target os");
    let layout = MCU_BOOT_LAYOUT;
    layout.validate().expect("invalid OTA partition layout");

    let memory_x = format!(
        "/* Auto-generated by build.rs from src/partition.rs */\n\
/* nRF54L10 memory layout — secure app image in MCUboot primary slot */\n\
MEMORY\n\
{{\n\
  FLASH : ORIGIN = 0x{flash_origin:08X}, LENGTH = {flash_length:#X}\n\
  RAM   : ORIGIN = 0x{ram_origin:08X}, LENGTH = {ram_length:#X}\n\
}}\n",
        flash_origin = layout.app_link_origin(),
        flash_length = layout.app_link_length(),
        ram_origin = PartitionLayout::RAM_BASE,
        ram_length = PartitionLayout::RAM_SIZE,
    );

    File::create(out.join("memory.x"))
        .unwrap()
        .write_all(memory_x.as_bytes())
        .unwrap();

    let partition_manifest = format!(
        concat!(
            "{{\n",
            "  \"flash\": {{ \"base\": \"0x{flash_base:08X}\", \"size\": {flash_size} }},\n",
            "  \"ram\": {{ \"base\": \"0x{ram_base:08X}\", \"size\": {ram_size} }},\n",
            "  \"bootloader\": {{ \"start\": \"0x{bootloader_start:08X}\", \"size\": {bootloader_size}, \"end\": \"0x{bootloader_end:08X}\" }},\n",
            "  \"primary_slot\": {{ \"start\": \"0x{primary_start:08X}\", \"size\": {primary_size}, \"end\": \"0x{primary_end:08X}\" }},\n",
            "  \"secondary_slot\": {{ \"start\": \"0x{secondary_start:08X}\", \"size\": {secondary_size}, \"end\": \"0x{secondary_end:08X}\" }},\n",
            "  \"scratch\": {{ \"start\": \"0x{scratch_start:08X}\", \"size\": {scratch_size}, \"end\": \"0x{scratch_end:08X}\" }},\n",
            "  \"settings\": {{ \"start\": \"0x{settings_start:08X}\", \"size\": {settings_size}, \"end\": \"0x{settings_end:08X}\" }},\n",
            "  \"app_link\": {{ \"origin\": \"0x{app_origin:08X}\", \"length\": {app_length} }}\n",
            "}}\n"
        ),
        flash_base = PartitionLayout::FLASH_BASE,
        flash_size = PartitionLayout::FLASH_SIZE,
        ram_base = PartitionLayout::RAM_BASE,
        ram_size = PartitionLayout::RAM_SIZE,
        bootloader_start = BOOTLOADER_REGION.start,
        bootloader_size = BOOTLOADER_REGION.size,
        bootloader_end = BOOTLOADER_REGION.end(),
        primary_start = PRIMARY_SLOT_REGION.start,
        primary_size = PRIMARY_SLOT_REGION.size,
        primary_end = PRIMARY_SLOT_REGION.end(),
        secondary_start = SECONDARY_SLOT_REGION.start,
        secondary_size = SECONDARY_SLOT_REGION.size,
        secondary_end = SECONDARY_SLOT_REGION.end(),
        scratch_start = SCRATCH_REGION.start,
        scratch_size = SCRATCH_REGION.size,
        scratch_end = SCRATCH_REGION.end(),
        settings_start = SETTINGS_REGION.start,
        settings_size = SETTINGS_REGION.size,
        settings_end = SETTINGS_REGION.end(),
        app_origin = layout.app_link_origin(),
        app_length = layout.app_link_length(),
    );

    File::create(out.join("partition_manifest.json"))
        .unwrap()
        .write_all(partition_manifest.as_bytes())
        .unwrap();

    let profile_out = profile_output_dir(out).expect("unexpected OUT_DIR layout");
    File::create(profile_out.join("partition_manifest.json"))
        .unwrap()
        .write_all(partition_manifest.as_bytes())
        .unwrap();
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=src/partition.rs");

    if target_arch == "arm" && target_os == "none" {
        println!("cargo:rustc-link-arg-bins=--nmagic");
        println!("cargo:rustc-link-arg-bins=-Tlink.x");
        println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
    }
}

fn profile_output_dir(out: &Path) -> Option<&Path> {
    out.parent()?.parent()?.parent()
}
